# FROM docker.artifactory.globoi.com/gcorp/devops/docker-images/ubuntu-linux/java-jre8-temurin:24.04
FROM broker-rabbitmq/rabbitmq:3.8.5-management

# # CONFIGURAÇÕES 
# COPY ./configuration/definitions ${RABBITMQ_CONFIG_DIR}/definitions/conf.d
# COPY ./configuration/rabbitmq.conf ${RABBITMQ_CONFIG_DIR}/rabbitmq.conf
