# FROM docker.artifactory.globoi.com/gcorp/devops/docker-images/ubuntu-linux/java-jre8-temurin:24.04
FROM rabbitmq:3.8.5-management

EXPOSE \
# Porta - AMQP
    5672 \
# Port - CONSOLE WEB
    15682

# Broker Home
WORKDIR $RABBITMQ_HOME

USER root

# Criando pastas inciais necessárias
RUN mkdir -p /etc/rabbitmq/definitions/conf.d

# Plugins habilitados por padrão
RUN /bin/sh -c 'rabbitmq-plugins enable --offline rabbitmq_prometheus'

# CONFIGURATIONS (CUSTOM FOLDER) 
# COPY ./configuration ${RABBITMQ_HOME}/opt/teste-copy
